# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:19
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Texto', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Fecha', models.DateTimeField(default=datetime.datetime(2016, 8, 20, 15, 19, 34, 700000, tzinfo=utc), verbose_name=b'Fecha de publicaci\xc3\xb3n')),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Texto', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Fecha', models.DateTimeField(default=datetime.datetime(2016, 8, 20, 15, 19, 34, 700000, tzinfo=utc), verbose_name=b'Fecha de publicaci\xc3\xb3n')),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
