# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0006_auto_20160820_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 16, 41, 7, 223486, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 16, 41, 7, 224485, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
