# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0008_auto_20160826_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='Fecha',
            field=models.DateField(auto_now_add=True, verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='Fecha',
            field=models.DateField(auto_now_add=True, verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
    ]
