# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0012_auto_20160917_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='Fecha',
            field=models.DateField(default=datetime.date(2016, 9, 17), verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
    ]
