# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0014_auto_20160917_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='Fecha',
            field=models.DateField(default=datetime.datetime(2016, 9, 17, 20, 32, 3, 607000, tzinfo=utc), verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
    ]
