# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0016_auto_20160917_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='Fecha',
            field=models.DateField(verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
    ]
