# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0017_auto_20160917_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=12)),
                ('nombre', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='entrada',
            name='Titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='Fecha',
            field=models.DateField(verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='Category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Mini_CMS.Categoria'),
            preserve_default=False,
        ),
    ]
