# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0019_auto_20160918_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='Category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Mini_CMS.Categoria'),
        ),
    ]
