# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_CMS', '0020_auto_20160918_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
