# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:26
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mini_CMS', '0002_auto_20160820_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('Texto', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('Fecha', models.DateTimeField(default=datetime.datetime(2016, 8, 20, 15, 26, 20, 192000, tzinfo=utc), verbose_name=b'Fecha de publicaci\xc3\xb3n')),
                ('Publicado', models.BooleanField()),
                ('urls', models.IntegerField()),
                ('Entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mini_CMS.Entrada')),
            ],
        ),
    ]
