# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:03
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20160820_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 21, 3, 55, 223000, tzinfo=utc), verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='Texto',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name='Texto'),
        ),
    ]
