# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20160827_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de publicaci\xc3\xb3n'),
        ),
    ]
